### ISSUE TITLE
Add parameterGroup to group parameters

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#115]
When I try to convert our cloud service spec to hydra spec, I find lots of definition have to convert into parameters.

For example, the old spec is something like below: 

```
application.commands: 
   stop: ''
   start: ''

application.package: 
   label: '2019'
   storageKey: demo-ruby.zip
   url: ''

  platform: 
    os: linux
    osVersion: '1.0'
    buildpack: ruby 2.x nodejs 10.xx
    category: Ruby

  application.option: 
    port: 3000
    maxStartDuration: 180

  application.healthCheck: 
    path: /
    port: ''
    intervalSeconds: 3

  hooks: 
    preStart: ''
    postinit: ''
```

after convert to hydra, it may like this:

```
apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
  name: ruby-app
  description: Customized version of ruby app
spec:
  variables:
    ...
  components:
    - componentName: ruby-app
      instanceName: ruby-app-instance-1
      parameterValues:
        - name: commandStop    
          value: ""
        - name: packageLable 
          value: "xx"
        - name: packageStorageKey or url     
          value:  demo-ruby.zip
        - name: platform-os
          value: linux
        - name: port 
          value: 3000
        - name: maxStartDuration     
          value: 180
        - name: healthcheck-xxx
          value: xxx
        - name: hooks-xxx
          value: xxx
    ...
```

I hope there is a parameterGroup, so that it can category my parameters. 

So the spec will be something like below:

```
apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
  name: ruby-app
  description: Customized version of ruby app
spec:
  variables:
    ...
  components:
    - componentName: ruby-app
      instanceName: ruby-app-instance-1
      parameterValues:
         - name: port 
            value: 3000
         - name: maxStartDuration     
            value: 180
        - parameterGroup: command 
           values:
              - name: Start
                 value: ""
             - name: Stop    
                value: ""
        - parameterGroup: package
           value:
               -name: label
                value: "xx"
               - name: StorageKey
                 value:  demo-ruby.zip
         - parameterGroup: platform 
            values:
               - name: os
                 value: aliyunlinux
               - name: osVersion
                 value: '2.x'
              - name: category
                value: Ruby
          - parameterGroup: healthcheck
            - values:
                   ...
          - parameterGroup: hooks
            values:
                ...
    ...
```

By that, **users can read and understand the spec better**.

What's more important is **the parameterGroup can give hydra some power to restrain and make users focus on what they need to care about**.

\cc @resouer
