### ISSUE TITLE
ComponentSchematic, or just Component

### ISSUE THREAD

**Issue by resouer** [oam-dev/spec#123]
Have we ever consider use `Component` only? For example:

```yaml
apiVersion: core.hydra.io/v1alpha1
kind: Component
metadata:
  name: azurefunction
  annotations:
    version: v1.0.0
    description: "Extended workflow example"
spec:
  workloadType: azure.com/v1.Function
  parameters:
  - name: github-token
    description: GitHub API session key
    type: string
    required: true
  workloadSettings:
    - name: source
      value: git://git.example.com/function/myfunction.git
    - name: github_token
      fromParam: github-token
```

Not sure if `ComponentSchematic` is the convention but looks like above YAML a bit better (at lease to me)?

:-)
