### ISSUE TITLE
Mounting config settings in volumes for containers

### ISSUE THREAD

**Issue by vturecek** [oam-dev/spec#14]
Currently, configuration settings for a component are handled through environment variables. The developer declares the environment variables required for a container workload, and (most likely) parameterizes them through the component's parameters for an operator to fill in at deployment time.

For certain types of configuration values, a file may be a better fit. For example:
 - sensitive information, like secrets and keys, that you don't want to show up in a process dump.
 - large structured configuration, like JSON documents or other files.

Users _could_ mount a volume and place files on disk, but there are multiple steps involved there just to get configuration settings into a container. Populating the contents from a secure storage location would also be an exercise left up to the user.

The spec could define a simple way to do this and potentially allow a way to define the source of configuration values combined with authentication to populate with secrets and keys.

One way we could do this is to include a "config" section under the component container config:

```yaml
apiVersion: hydra/v1alpha
kind: ComponentSchematic
metadata:
  description: ""
spec:
  workloadType: ReplicableService
  containers:
  - name: my-container
    image:
      name: vturecek/mycontainer:1.0.0
      digest: sha256:6c3c624b58dbbcd3c0dd82b4c53f04194d1247c6eebdaab7c610cf7d66709b3b
    env:
    - name: BACKEND_ADDRESS
      fromParam: 'backend-address'
    config:
    - name: USERNAME
      fromParam: 'username'
    - name: PASSWORD
      fromParam: 'password'
```

The result of this would be two files mounted on a local volume with names USERNAME and PASSWORD, and the contents of each file would be the corresponding value.

The runtime would be responsible for mounting the volume locally and populating its contents each time the container instance is created.
