### ISSUE TITLE
Proposal: Extract image tag/digest to it's own attribute to enable parameterization

### ISSUE THREAD

**Issue by mikkelhegn** [oam-dev/spec#146]
To ease the instantiation of a component using never versions of the container images, we should move the tag and digest part of the image attribute to it's own attribute, making it easier to parameterize that part of the attribute.

From
```
  containers:
  - name: my-twitter-bot-frontend
    image:
      name: krancour/my-twitter-bot-frontend:1.0.0
```

To
```
containers:
  - name: my-twitter-bot-frontend
    image:
      name: krancour/my-twitter-bot-frontend
      tag: "[fromParam(imageTag)]"
```
