### ISSUE TITLE
What if Developer has opinion to Traits?

### ISSUE THREAD

**Issue by resouer** [oam-dev/spec#153]
It happens that a Dev may have some opinion about the Traits for this application. 

More generally, the Dev (who understand how the app is developed in code level) may want to communicate with Ops (who generally understand the app but not so deeply as Dev) thru Hydra spec.

Let's say, a Dev has below opinion about scaler Trait:

```
My awesome application only need to scale when it is SUPER busy.
```

> Note that this opinion deeply depends on the code of this app, so the Ops has no such knowledge unless a Dev tells him personally. 

Below is available Traits in the platform:

```
traits:
  - name: SuperBusyScaler
     properties:
         cpuUsage: 90

traits:
  - name: LessBusyScaler
     properties:
         cpuUsage: 60
```

So ideally, the one who create `ApplicationConfiguration` is expected choose to use `SuperBusyScaler` Traits, while note that currently we have [following practice](https://github.com/microsoft/hydra-spec/blob/master/6.application_configuration.md#runtime-and-application-configuration):

> Conceptually speaking, an application configuration is managed as part of the application operator role. It has three main sections:

**Thus raise this issue we want to discuss here:**

How application operator role know about operation opinions from app developer then?
