### ISSUE TITLE
How Traits can be composed in order？

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#235]
Now in rudr, we have implementation to manage whether the trait manager need to execute trait before Component create/modify/delete or after.

So I suggest we add field like `stage` in Trait to define the compose order.

```
apiVersion: core.oam.dev/v1alpha1
kind: Trait
metadata:
  name: Ingress
  annotations:
    version: v1.0.0
spec:
  stage: afterStart/afterModify
  appliesTo:
    - Server
  parameters:
     ...
```

```
apiVersion: core.oam.dev/v1alpha1
kind: Trait
metadata:
  name: Autoscaler
  annotations:
    version: v1.0.0
spec:
  stage: preStart/preModify
  appliesTo:
    - Server
  parameters:
     ...
```
