### ISSUE TITLE
describe component/trait version in AppConfig

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#237]
Now we have versions in annotation both `Trait` and `Component`, but we didn't define them in AppConfig, so we don't know which version of Trait/Component was used in AppConfig.

Have version explicitly defined in AppConfig has two benifits:

1. when we change ComponentSchemic, the runtime could change the version in it's component. After that, when we need to upgrade this Component, we could change the component version in AppConfig.
2. the same with trait, when we upgrade trait, we could also use the version of trait in AppConfig to let the app operator tell which version he want's to use.

**Comment by vturecek** [comment]
Agreed, we do need a way to allow application operators to specify the version of a component, trait, and scope to use. 

The assumption here is that a runtime can have multiple versions of a component schematic, trait definition, and trait definition registered. We can state this explicitly in the spec by saying that a fully-qualified unique identifier for a component schematic, trait definition, and scope definition is:

`metadata.name` + `annotations.version`

For example, the fully-qualified name for this component schematic:

```yaml
apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: frontend
  annotations:
    version: v1.0.0
    description: >
      Sample component schematic that describes the administrative interface for our Twitter bot.
spec:
  ...
```
would be `frontend.v1.0.0`

The runtime would need to track this. It might require some additional munging of the OAM spec files to get it to work in each runtime.

In the Application Config, `name` and `version` can be separate fields, or we can combine into one. I would vote for separate fields so that app operators don't need to refer to the OAM spec to know the format of a combined value.
