### ISSUE TITLE
how to manage config file in OAM

### ISSUE THREAD

**Issue by joeylin** [oam-dev/spec#251]
when I use k8s, I cloud use configmap to manage config files, and map them to container, at last my app can read them. But in OAM, I can not find something like this, what i can do is transfer my config file content to string, and use configfile field on Component spec, and map them to container

this experience is very poor，it hard to debug when there is a misconfiguration, and hard to manage config file, and also make oam yaml file difficult to read

![image](https://user-images.githubusercontent.com/2030833/68385649-38079f80-0195-11ea-9cd1-ac0cff75df96.png)

**Comment by wonderflow** [comment]
Maybe we could add some field like `reference`, that could let runtime to decide which kind of real resource to get.

**Comment by resouer** [comment]
@joeylin This is an issue we discussed for a while, and one solution is we need to define a _ConfigurationSource_ object in OAM. e.g.:

```yaml
...
config:
  - path: "/etc/access/default_user.txt"
    source: "my-config"  # This is the name of a ConfigurationSource object
    overwritable: false
```

And Dev would be responsible for defining the _ConfigurationSource_ object:

```yaml
apiVersion: core.oam.dev/v1alpha1
kind: ConfigurationSource
metadata:
  name: my-config
spec:
  encrypted: none
  value: 
    game.properties: |
      enemies=aliens
      enemies.cheat=true
 ... 
```
Note that you still need the same process of writing a K8s `ConfigMap` to write this _ConfigurationSource_ yaml.

The motivation is to decouple config data from description in OAM spec.

WDYT?

**Comment by resouer** [comment]
ref: https://github.com/oam-dev/spec/issues/90

**Comment by wonderflow** [comment]
I agree with this:

```
config:
  - path: "/etc/access/default_user.txt"
    source: "my-config"  # This is the name of a ConfigurationSource object
    overwritable: false
```

`source` here is `reference ` I said

**Comment by hongchaodeng** [comment]
My 2c: Why not define _ ConfigurationSource_ as a Trait?
We can attach config traits to app components just like mounting configMap to pods.

**Comment by hongchaodeng** [comment]
Additionally, I wouldn't suggest we put entire data blocks in OAM types.
K8s secrets does this job well and we could reuse and reference it:

```yaml
traits:
- name: ConfigSource
  properties:
    secretKeyRef: my-k8s-secret
```
