### ISSUE TITLE
properties and parameters of ApplicationScopes

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/spec#266]
In _6.application_configuration.md_ , the section of scopes defines _properties_ for operator to override properties exposed by a scope.
> ### Scope
> The scope section defines application scopes that will be created with this application configuration.
> 
> | Attribute | Type | Required | Default Value | Description |
> |-----------|------|----------|---------------|-------------|
> ...
> | `properties` | [`Properties`](#properties) | N | | Overrides of properties that are exposed by this scope. |

But in _4.application_scopes.md_ , in the section of _spec_ of _Application Scopes_ , it seems there's no definition of _properties_ but only _parameters_ .

> ### Spec
> 
> The spec defines the constituent parts of a scope. 
> 
> | Attribute | Type | Required | Default Value | Description |
> |-----------|------|----------|---------------|-------------|
> ...
> | `parameters` | [`[]Parameter`](#parameter) | N | | The scope's configuration options. |

Additionally, related situation in Examples _6.application_configuration.md_ 
One is _properties_ while the other one is _parameters_.
```yaml
...
  scopes:
    - name: network
      type: core.oam.dev/v1alpha1.Network
      properties:
        - name: network-id
          value: "[fromVariable(networkName)]"
        - name: subnet-ids
          value: "my-subnet1, my-subnet2"
```

```yaml
...
  scopes:
    - name: core.oam.dev/v1alpha1.Network
      parameterValues:
        - name: PARAM_NAME
          value: SUPPLIED_VALUE
...
```
