### ISSUE TITLE
align Trait.Properties/Scope.Properties or other field whose type defined by jsonschema to be an object 

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#293]
For example:

Below is a trait example:

This is valid case:

```
traits:
  - name: manualScaler
     properties:
        replicaCount:  2
```

This is invalid:
```
traits:
  - name: manualScaler
    properties:
      - name: replicaCount
         value: "2"
```

We should point it out in spec.

/cc @hongchaodeng
