### ISSUE TITLE
Add "Standard" WorkloadType

### ISSUE THREAD

**Issue by abchow** [oam-dev/spec#303]
As per discussion of the "OAM Resource Composition Proposal" on 2020-01-28 community meeting, since workload such as Serverless Function and VM are supported via Extended WorkloadType, by not enforcing schema on Extended WorkloadType, there will not be a standard for these workload types across OAM Runtime providers and will lead to support issues in the future.

The proposed solution is to add a new WorkloadType - Standard WorkloadType.  

* Core WorkloadType - Enforce Schema and Required to support by OAM providers
* Standard WorkloadType - Enforce Schema but Optionally supported by OAM providers
* Extended WorkloadType - Not enforce schema and Optionally supported by OAM providers

Some of the suggested Standard WorkloadType are Serverless Function and VM.

**Comment by ryanzhang-oss** [comment]
Thanks Abelard. I think we will incorporate this  into our new spec. However, I wouldn't say it's a new workloadType but more like a new group/category of workloadType.

**Comment by abchow** [comment]
Thanks Ryan.  Let me update the description.

**Comment by mnbf9rca** [comment]
Did this get anywhere? does anyone have any example schemas for standard or extended workload types like serverless functions (azure functions), Azure Data FActory Pipelines, Azure Webapp etc.?

**Comment by resouer** [comment]
@mnbf9rca Can't speak for MFST, but we do have AlibabaCloud FaaS workload (extended) as below:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: function-frontend
spec:
  workload:
    # this is a real FaaS workload in Alibaba
    apiVersion: faas.alibaba.com/v1
    kind: Function
    spec:
      runtime: java8
      timeoutMilliseconds: 3000
      blobCodeUrl: http://xxx/f36286e6-f070-498f-a520-6dd3a589bd90
      env:
        - name: debug
          value: "true"
      resources:
        cpu:
          required: 1
        memory:
          required: 2048M
      triggers:
        - type: http
        - type: metaq
```

The controller to make it runnable is still under process of open source.

We don't have many standard workload today, but we are very willing to know if any candidate the community is looking at.
