### ISSUE TITLE
Built-in support for managing secrets

### ISSUE THREAD

**Issue by Haishi2016** [oam-dev/spec#308]
It's desirable that OAM provides native support for describing secrets such as passwords and certificates.

**Comment by bericoberin** [comment]
This is critical.  putting plain passwords and tokens in plain text is really really bad.

**Comment by resouer** [comment]
@bericoberin Yes, we fully agree! While note that users can use `secretKeyRef` in [OAM Kubernetes runtime.](https://github.com/crossplane/oam-kubernetes-runtime). For example, feel free to define a component like below:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: frontend
  annotations:
    description: Container workload
spec:
  workload:
    # a k8s workload CR
    apiVersion: apps/v1
    kind: Deployment
    spec:
  containers:
    - name: web
      image: php:latest
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
```
The `mysecret` Secret object will be managed by infra engineer or auto-generated by some other component (e.g. a MySQL component).

@Haishi2016 Would like to know your idea around how secret can be modeled better in OAM model. Please check the scenario of data input/output PR which should be closely related to this discussion: https://github.com/crossplane/oam-kubernetes-runtime/pull/53/file

In that proposal, we can achieve data input/output, but the developer still need to claim the secret key explicitly because we can't model `Secret` for now. If we could, we can achieve very nice user experience because use only need to claim the ENV key and OAM runtime could inject everything it needs automatically. /cc @wonderflow , maybe you two could sync offline about this issue.
