### ISSUE TITLE
Reconciling OAM traits in v1alpha2

### ISSUE THREAD

**Issue by negz** [oam-dev/spec#323]
#### Background

My understanding is that currently in the Rudr implementation of the v1alpha1 OAM spec all knowledge of how to render an `ApplicationConfiguration` into into Kubernetes specific kinds (e.g. `Deployment` and `Service`) is centralised in one controller (or rather [instigator](https://github.com/oam-dev/rudr/blob/d674dc50d24ee18125d007e33b2ada3a5e23eeaf/src/instigator.rs)). I don't speak Rust, but it appears that this controller:

1. Watches for `ApplicationConfiguration`
1. Gets each `ComponentSchematic` referenced by the `ApplicationConfiguration`
1. Creates, updates, or deletes Kubernetes resources as appropriate to satisfy the workload described by the `ComponentSchematic`. For example by rendering and creating a `Deployment`, `Service`, etc.
1. Creates, updates, or supplements the Kubernetes resources produced in step 3 per the traits associated with the component that produced them.

This allows a lot of flexibility because one controller is authoritative for everything to do with an `ApplicationConfiguration`, but could impact the maintainability and extensibility of the code. The `exec` method of the instigator is ~300 lines long, and support for new kinds of workloads and traits must be compiled into the instigator.

In the [nascent Crossplane implementation](https://github.com/crossplane/crossplane/pull/1321) of the v1alpha2 OAM spec an `ApplicationConfiguration` is reconciled by _a series of controllers_.  The `ApplicationConfiguration` controller:

1.  Watches for `ApplicationConfiguration`.
1. Gets each `Component` referenced by the `ApplicationConfiguration
1. Renders the `Component` into a Kubernetes CR representing its workload kind, e.g. `ContainerizedWorkload`.

At this point the job of reconciling the OAM workload is passed onto a workload-specific controller. For example a `ContainerizedWorkload` controller might:

1. Watch for `ContainerizedWorkload`
1. Create a `Deployment` and a `Service` for each `ContainerizedWorkload`

Note that the `ApplicationConfiguration` controller is, in a way, completely workload-unaware. It simply renders out a templated workload and defers the task of figuring out how to reconcile that workload into another controller.

Currently there is not a lot of clarity around how traits will be supported under this new approach. It's not possible (or, in my opinion, desirable) to have the `ApplicationConfiguration` controller parse and act on traits as the current Rudr implementation does. The `ApplicationConfiguration` controller doesn't know that a `ContainerizedWorkload` produces a `Deployment`, so it cannot know that it should modify the `spec.replicas` of a `Deployment` when it encounters a `ManualScalerTrait` in the `spec.components[0].traits` array of an `ApplicationConfiguration`.

#### Proposal

I recommend that the `ApplicationConfiguration` controller instantiate each trait it encounters and create a reference from that trait CR to the workload CR that was produced by its component. For example given the below `Component` and `ApplicationConfiguration`:

```yaml
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
      - name: example
        image: example:latest
  parameters:
  - name: instance-name
    required: true
    fieldPaths:
    - metadata.name
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
  - componentName: example-component
    parameterValues:
    - name: instance-name
      value: example-workload
    traits:
    - trait:
        apiVersion: core.oam.dev/v1alpha2
        kind: ManualScalerTrait
        metadata:
          name:  example-trait
        spec:
          replicaCount: 3
```

The `ApplicationConfiguration` controller would:

1. Render and create a `ContainerizedWorkload` CR named `example-workload`.
1. Render and create a `ManualScalerTrait` CR named `example-trait`.

The rendered `ManualScalerTrait` CR would contain a reference to the workload it applies to, for example:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ManualScalerTrait
metadata:
  name:  example-trait
spec:
  replicaCount: 3
  workloadRef:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    name: example-workload
```

This would allow us to encapsulate the logic of how to reconcile each kind of trait into one or more _trait controllers_. For example it would be possible to use a [watch predicate](https://godoc.org/github.com/crossplane/crossplane-runtime/pkg/resource#PredicateFn) to write a small controller that watched for instances of `ManualScalerTrait` whose `spec.workloadRef.kind` was `ContainerizedWorkload`. I believe this is a reasonable approach because it:

* Decentralises the logic required to process each kind of trait.
* Allows the `ApplicationConfiguration` and workload controllers (like `ContainerizedWorkload`) to be trait-unaware. For example a trait could apply to a Crossplane `RedisCluster`, or a KNative `Service` even if those CRs and controllers were completely OAM unaware.
