### ISSUE TITLE
Workload metadata vs spec? Workload name?

### ISSUE THREAD

**Issue by artursouza** [oam-dev/spec#333]
### Issue
What is the use of workload name in Component? There is only one workload per Component, so what is the reason for metadata AND spec? Name seems useless when consuming a Workload in Component and all configuration of the workload goes into spec.
### Proposal
Remove metadata when consuming Workload or make metadata optional.

**Comment by negz** [comment]
There is a one-to-many Component-to-Workload relationship. Think of a Component as a template an ApplicationConfiguration may use to produce a Workload. When N ApplicationConfigurations reference 1 Component N instances of the Workload will be produced. So, the use of the workload name is to specify, given an ApplicationConfiguration, what the workload should be named.

I think the current implementation is pretty flexible.

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: coolcomponent
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: potato
```

You could write the above, but doing so would only make sense if the Component was only used by exactly one ApplicationConfiguration. When a second ApplicationConfiguration attempted to use the Component it would fail, because it would try to create a ContainerizedWorkload named "potato" when one already existed (and was controlled by another ApplicationConfiguration).

Instead it's usually better to write:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: coolcomponent
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
  parameters:
  - name: instance-name
    description: Name of this workload
    required: true
    fieldPaths:
    - metadata.name
```

Thus allowing multiple ApplicationConfigurations to reuse the same Component, as long as each ApplicationConfiguration specifies a unique name for the workload the Component will produce.

We might consider making a Component's `spec.workload.metadata` optional, but recall that objects are uniquely identified by their group, kind, and name. If `spec.workload.metadata` were optional we'd need some deterministic way to name each workload that remained stable over time. I considered:

* `appconfigname-componentname` - Limits the appconfig to using each component at most once.
* `appconfigname-componentname-componentindex` (where index is the component's position within the appconfig's array of components) - Requires the array of components that an appconfig references to remain fixed for the lifetime of the appconfig.

**Comment by artursouza** [comment]
This is the part where it was not obvious. Does it mean an app with multiple components can also be represented as a component with multiple workloads?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by negz** [comment]
> Does it mean an app with multiple components can also be represented as a component with multiple workloads?

I'm not sure if I understand what you're asking, but I think the answer is no. 😄

Each component may include a template for only one workload. It's not possible for one ApplicationConfiguration to reference one Component one time to produce three Workloads. An ApplicationConfiguration _could_ reference one Component three times to produce three Workloads.

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: coolapp
spec:
  components:
  - componentName: coolcomponent
    parameterValues:
    - name: instance-name
      value: coolapp-coolworkload
```

The above appconfig references one component one time. The referenced component must contain a template for exactly one workload, so this appconfig will always produce one workload.

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: coolapp
spec:
  components:
  - componentName: coolcomponent
    parameterValues:
    - name: instance-name
      value: coolapp-coolworkload-a
  - componentName: coolcomponent
    parameterValues:
    - name: instance-name
      value: coolapp-coolworkload-b
```

The above appconfig references one component two times (notice both entries in the `spec.components` array refer to `componentName coolcomponent`). The referenced component must contain a template for exactly one workload, so this appconfig will always produce two workloads.
