### ISSUE TITLE
OAM component versioning mechanism

### ISSUE THREAD

**Issue by ryanzhang-oss** [oam-dev/spec#336]
An application Configuration author does not have a way to point to a specific version of a component in the current [spec](https://github.com/oam-dev/spec/blob/1.0.0-alpha2/).  The reason is that OAM spec uses a component's name as the only information to reference to it.

This is needed in **any mission-critical production services** that utilize roll-back as the default emergency backup. In this case, they need a way to specify a previous `version` during the rollback. One can work around this issue if they are willing to take the risk and roll-forward their deployment. However, this is not the case in most of the cloud services providers.

Moreover,  a real workload in the OAM v1alpha2 spec is generated by templating a component with values filled in an applicationConfig. Therefore, this two-level composition nature of a workload makes it more difficult to expose the real version of a component. Here, we will add three proposals below that can solve this problem.

**Comment by negz** [comment]
Some mechanical implementation feedback:

* Kubernetes runtimes can't add arbitrary metadata fields. So no Kubernetes runtime could support setting `metadata.version` on `Component`.
* Kubernetes objects (and I believe OAM objects under the current spec) are uniquely identified by API group, kind, and name (within their namespace). It's within our power to change this for OAM, but not for Kubernetes. So we can't actually lookup a named component by version, nor can multiple versions of the same named component exist at one time.

This isn't to say that we shouldn't _have_ versions; just that the initial proposal isn't feasible.

**Comment by resouer** [comment]
My original idea was revision is implicit" in OAM, but it's tricky in ref model (the main reason Matt put a "name+version" example in current spec).

My current thinking is the version could be annotated on `Component` and version data mapping will be recorded by an independent internal object.  Let's say: [ControllerRevision](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#controllerrevision-v1beta2-apps). 

The controller is responsible for tracking and maintaining the `ControllerRevision` list during `Component` rollout/rollback and choose correct object data. Of course in detail, I assume it will probably only translate different revisions into operations to underlying Deployment and let Rollout Trait controller to perform rollout/rollback (didn't think deeply).

@ryanzhang-oss you could check [the code of StatefulSet](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go) for `ControllerRevision` usage, should be straightforward.

**Comment by hongchaodeng** [comment]
I agree with @resouer and propose similar thoughts in https://github.com/oam-dev/spec/issues/342#issuecomment-605500233

Let's continue discussion there.

**Comment by ryanzhang-oss** [comment]
We need a way to assign a version to a workload instance if we want to support upgrade in OAM.  We have a separate [discussion](https://github.com/oam-dev/spec/issues/341) on whether we need to support upgrade.  Assuming that we need to, here are the more concrete design proposals from Alibaba.

**Backgound**
Current OAM creates a workload instance through two steps. 
1.  It locates the component definition by its name.
2. It instantiates the component definition template by replacing the component parameters with the values specified in the appConfiguration.
This means that the real workload instance revision is not the same as the component version.
Here is an example
```yaml
kind: Component
metadata:
  name: web-service
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers
        -name: c
         image: default
         port: 8080
  parameter:
     - name: image
       fieldPaths:
         - spec.containers[0].image 
 ---
kind: ApplicationConfiguration
spec:
  components:
  - componentName: web-service
    parameterValue:
     - name: image
       value: nginx:v3
```

The actual instance of a workload is 
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ContainerizedWorkload
spec:
  containers
    -name: c
     image: nginx:v3
     port: 8080
```
We propose that we require an OAM platform to track the revisions of the generated workload instances. OAM users can list/get the revision history of a workload so that they can perform upgrade/rollback operations.

**Comment by ryanzhang-oss** [comment]
However, since the workload instances are generated with a combination of a specific component and a specific appConfig revision, we have two designs to generate the revision of a single workload.

**Maintain two revisions**
In this version, a component is mutable. An OAM platform will implement a way to internally track each revision of a component. Each revision is basically a snapshot of a component. Here is a concrete example.

```yaml
---
## v1
kind: Component
metadata:
  name: web-service
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers
        -name: c
         image: default
         port: 8080
  parameter:
     - name: image
       fieldPaths:
         - spec.containers[0].image 
---
## v2
kind: Component
metadata:
  name: web-service
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers
        -name: c
         image: nginx:latest
         port: 8080
```

OAM platform generates the below two objects internally
```yaml
kind: ComponentRevision
metadata:
  name: web-service-v1
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers
        -name: c
         image: default
         port: 8080
  parameter:
     - name: image
       fieldPaths:
         - spec.containers[0].image 
---
kind: ComponentRevision
metadata:
  name: web-service-v2
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      field: v2
  parameter:
     - name: image
       value: nginx:v2 
````

**Comment by ryanzhang-oss** [comment]
**Create the workload instance **
In this proposal, a component is **immutable**. We instead propose to make applicationConfig a developer-centric resource to describe all the instantiated components in an application. For example

```yaml
---
kind: Component
metadata:
  name: web-service-v1
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers
        -name: c
         image: default
         port: 8080
  parameter:
     - name: image
       fieldPaths:
         - spec.containers[0].image 
---

```

**Comment by henrywangx** [comment]
So, is there any conclusion about this?
Looks like many people need to do upgrade, traffic management. 
It's better to be a standard spec.

**Comment by ryanzhang-oss** [comment]
> So, is there any conclusion about this?
> Looks like many people need to do upgrade, traffic management.
> It's better to be a standard spec.

We are going to discuss this in our community meeting, you are welcome to join.

**Comment by ryanzhang-oss** [comment]
**Create the workload instance** 
In this proposal, a component is **immutable**. We instead propose to use a new a developer-centric resource to describe all the instantiated components in an application. For example, an app developer can create the two resources below

```yaml
---
kind: Component
metadata:
  name: web-service-v1
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers
        -name: c
         image: default
         port: 8080
  parameter:
     - name: image
       fieldPaths:
         - spec.containers[0].image 
---
kind: ComponentInstance
spec:
  components:
  - componentName: web-service-v1
    parameterValue:
     - name: image
       value: nginx:v3
```
We ask OAM platforms to track the revisions of the ComponentInstance so we will have 
```yaml
kind: ComponentInstanceRevision
meta:
    name: web-service-v1-v3
spec:
  components:
  - componentName: web-service-v1
    spec:
       apiVersion: core.oam.dev/v1alpha2
       kind: ContainerizedWorkload
      spec:
          containers
            -name: c
              image: nginx:v3
              port: 8080
```
Finally, an OAM operator will create the applicationConfiguraiton
```yaml
kind: ApplicationConfiguration
spec:
  components:
  - ComponentRevision: web-service-v1-v3
     traits:
      - trait:
        traffic:
        - revision: web-service-v1-v3
          weight: "60%"
        - revision: web-service-v1-v2
          weight: "30%"
        - revison: web-service-v1-v1
          weight: "10%" 
```
Pro: This is a more explicit way to express workload versions. It also clearly defines the role of an application developer vs an operator.
Con: This approach changes the current specs user experience greatly. It is also not easy to make a component immutable in practice.

**Comment by artursouza** [comment]
I would not add a new concept to handle version (or revision). Versioning components make more sense IMO. It is easier to understand. I saw the comment about it not being supported in Kubernetes - that can be handled at the implementation layer: to have the implementation of the spec to append the version to the name automatically but the spec itself keeps the separation between name and version. I am in favor of the original idea with minor changes:

Component
```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: my-web-app-component
  version: v1.0.2
  annotations:
    description: >
      Sample component schematic that describes the administrative interface for our Twitter bot.
spec:
  workload:
 ...
```
ApplicationConfig
```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: my-app-deployment
spec:
  components:
    - name: my-web-app-component
       version: v1.0.2
       parameterValues:
   .... 
```
