### ISSUE TITLE
[Proposal] - introduction of Deployment

### ISSUE THREAD

**Issue by Haishi2016** [oam-dev/spec#342]
(It's been mentioned during other discussions but I want to put up a separate proposal for it)

# Overview

Conceptually, ApplicationConfiguration serves for several purposes - it describes application topology, it describes configurations, and it represents a deployed unit. With the new application concept, which is being tracked in another proposal, we are separating the first two responsibilities. This proposal proposes we separate representation of a deployed unit out of ApplicationConfiguration and formally introduce a **Deployment** (or Application Instance) object.
A **Deployment** object represent a specific instantiation of an application. It captures information that is relevant to a particular deployment. This will be a natural place to describe rolling updates, canary deployments, blue/green deployments etc.

# Spec
 
The simplest Deployment could be as simple as referencing to an application version:

```yaml
apiVersion: core.oam.dev/v1alpha3
kind: Deployment
metadata:
  name: production
spec:
  versions:
     - name: v1
       applicationRef: 
       - name: my-app
          version: v1
```

And the following sample shows how to describe a canary deployment:

```yaml
apiVersion: core.oam.dev/v1alpha3
kind: Deployment
metadata:
  name: canary
spec:
  versions:
     - name: v1
       applicationRef: 
       - name: my-app
          version: v1
    - name: v2
       applicationRef: 
       - name: my-app
          version: v2
  components:
   - website
  traffic:
  - version: v1
     weight: 70%
  - version: v2
     weight: 30%
  policy:
     primary: v1
     secondary: v2
     rollback:
        errors: 10%
        interval: 1m
     promotion:
        step: 40%
        success: 80%
        interval: 1m
```
Note that the above sample assumes ingress/load-balancer being a built-in concept of the new Application object hence is not explicitly specified here. If this is not the case, we'll need to add a reference to an ingress trait. 

# Value
* Formally separates abstract description of an application and an instance of an application
* Rich language for describing complex deployment scenarios on one or multiple versions

# Implications for a control plane implementation
*  The deployed unit of an application is a Deployment instead of an ApplicationConfiguration

**Comment by ryanzhang-oss** [comment]
Thanks, Haishi. We (Alibaba) already used OAM to describe upgrade/rollback.  In our practice, we apply a trait to a component as a descriptive.  Here are my main take away
1.   Component deployment is mostly application operators' concern and decoupled from the logic of the component. Thus, it seems to be a very natural candidate to be described as a Trait.
2. The cost of introducing another type of object seems to out weight the benefit if any. A trait can have all the fields this deployment object has.  We have already implemented rollout/canary traits supporting more features.
3. I am not sure how does the deployment solve the problem to upgrade a micro-service application mentioned in https://github.com/oam-dev/spec/issues/341

**Comment by Haishi2016** [comment]
My problem with leaving it all to traits is that the trait system is a very generic system. Yes it's capable of describing any intention but none of those is on OAM model. Hence, the semantic meanings of these traits subject to specific implementation/interpretation.  To me, for OAM to have value that is broadly applicable to everyone, we have to provide common abstractions and concepts as the OAM model itself. Otherwise, we have an model that can be powerful when backed by a specific implementation but powerless otherwise. And there are no guaranteed consistent behavior across implementations because too much is relying on implementations.

**Comment by ryanzhang-oss** [comment]
> or OAM to have value that is broadly applicable to everyone, we have to provide common abstractions and concepts as the OAM model itself. Otherwise, we have an model that can be powerful when backed by a specific implementation but powerless otherwise. And there are no guaranteed consistent behavior across implementations because too much is relying on implementations.

Agree.  However, isn't standard traits/scope/workload the OAM way to provide that common abstraction and portability?

**Comment by Haishi2016** [comment]
Rolling updates or canary deployments involve multiple versions of an app/component. How do you apply a trait to multiple version of the same component?

**Comment by ryanzhang-oss** [comment]
> Rolling updates or canary deployments involve multiple versions of an app/component. How do you apply a trait to multiple version of the same component?

That's the reason we are proposing https://github.com/oam-dev/spec/issues/336. I will update that issue with more detailed examples

**Comment by Haishi2016** [comment]
Hey @ryanzhang-oss, can you please provide an example of a trait describing rolling update or canary deployment? It will help me to understand how you envision to express such scenarios. Thanks.

**Comment by negz** [comment]
Naming nitpick: When there are two kinds of the same name in different API groups (e.g. `kind: Deployment, group: apps`, and `kind: Deployment, group: core.oam.dev`) I believe `kubectl get deployments` will show (only) the custom resources of the lexicographically first API group. That is to say, we probably don't want to use `kind: Deployment`, because it would cause confusion for any OAM runtime built on the Kubernetes API server.

**Comment by hongchaodeng** [comment]
>  When there are two kinds of the same name in different API groups (e.g. kind: Deployment, group: apps, and kind: Deployment, group: core.oam.dev)

We should coin a new name, like _AppDeployment_.

**Comment by hongchaodeng** [comment]
I like this proposal. I think the _Deployment_ described above is very close to the ComponentRevision in https://github.com/oam-dev/spec/issues/336.

Let me put some examples to describe ComponentRevision:

```yaml
kind: ComponentRevision
metadata:
  name: web-service
spec:
  versions:
  - name: v1
    component: old
  - name: v2
    component: new
```
In this way, we can keep a history of all revisions that's been rollout.

So we can describe traffic shifting and canary rollout traits like:
```
kind: ApplicationConfiguration
spec:
  components:
  - revisionName: web-service
    traits:
    - trait:
        
```

**Comment by hongchaodeng** [comment]
I like this proposal. I think the _Deployment_ described above is very close to the ComponentRevision in https://github.com/oam-dev/spec/issues/336.

Let me put some examples to describe ComponentRevision:

```yaml
kind: ComponentRevision
metadata:
  name: web-service
spec:
  versions:
  - name: v1
    component: old
  - name: v2
    component: new
```
In this way, we can keep a history of all revisions that's been rollout.

So we can describe traffic shifting and canary rollout traits like:
```yaml
kind: ApplicationConfiguration
spec:
  components:
  - revisionName: web-service
    traits:
    - trait:
        traffic:
        - revision: v1
          weight: "70%"
        - revision: v2
          weight: "30%"
    - trait:
        canary:
          source: v1
          target: v2
          analysis:
            interval: 1m
            errorThreshold: "10%"
            metrics:
            - name: request-success-rate
              thresholdRange:
                min: "99%"
              interval: 1m
```

**Comment by wonderflow** [comment]
The idea of `ComponentRevision` is really good and this don't add concept burden to OAM

**Comment by Haishi2016** [comment]
In that case, should we consider renaming ApplicationConfiguration to AppDeployment?

**Comment by wonderflow** [comment]
> In that case, should we consider renaming ApplicationConfiguration to AppDeployment?

Not necessary I think. Both of them can be understood as a deployment thing

**Comment by Haishi2016** [comment]
Well, if it's an deployment why don't just call it deployment. I recommend to use straightforward terms that don't need implied knowledge or understanding. "Configuration" at surface has no connection to a "Deployment", though under OAM it's **implied** that when you deploy you deploy an ApplicationConfiguration. I think we should try to reduce such subtle indirection.

**Comment by resouer** [comment]
Thanks @Haishi2016 , it seems interesting, several questions in my mind:

(1) what's its relationship with existing OAM concepts (i.e. Components/Traits/AppConfig)., specifically: 
  - what does `applicationRef` reference to, a Component, or a ApplicationConfiguration?
  - how `traffic` relates to Trait?

(2) what's benefit of such a Deployment vs a ApplicationConfiguration? 

Note that with ##336 addressed, we should be able to use `ApplicationConfiguration` to model such Deployment. Also, for:
> ... we have to provide common abstractions and concepts as the OAM model itself.

It seems [standard workloads](https://github.com/oam-dev/spec/blob/77e5d2aa52dfd7cc11c754b8199f4f34eb866e81/3.workload.md#standard-workload) + [standard traits](https://github.com/oam-dev/spec/blob/77e5d2aa52dfd7cc11c754b8199f4f34eb866e81/6.traits.md) could achieve this goal.

For the naming, I strongly agree with @negz , but I hope we can change ApplicationConfiguration to ApplicationDeployment (and echo my question (2) above).

**Comment by Haishi2016** [comment]
I'm okay if we use #336 in conjunction with ApplicationConfiguraiton to model such deployment, as long as we can rename ApplicationConfiguration to ApplicationDeployment or AppDeployment.

**Comment by resouer** [comment]
@Haishi2016 yeah that's the current idea in my mind.

Would you like to work on #336 to design how we can model revision in detail? We can work together to make it a concrete proposal.

**Comment by Haishi2016** [comment]
Sure.

**Comment by ryanzhang-oss** [comment]
> Hey @ryanzhang-oss, can you please provide an example of a trait describing rolling update or canary deployment? It will help me to understand how you envision to express such scenarios. Thanks.

Hi,  please take a look at https://github.com/oam-dev/spec/issues/336 , I have added a detailed design proposal.

**Comment by draveness** [comment]
> For the naming, I tend to agree with @negz , but I hope we can change ApplicationConfiguration to ApplicationDeployment (and echo question (2) above).

+1 on renaming to `ApplicationDeployment`, the `ApplicationConfiguration` sounds like a configuration data of an application to me in the first place.

**Comment by resouer** [comment]
@draveness ApplicationConfiguration is indeed the configuration for the app. Essentially, in OAM, there are two parts:

1. Application = A bunch of Components, ref: https://github.com/oam-dev/spec/issues/334
2. ApplicationConfiguration = Apply operational capabilities to Components

The ApplicationDeployment is a "UI object" to generate Application and ApplicationConfiguration.

**Comment by resouer** [comment]
Add this in milestone which is closely related to application level rollout and revisioning.

**Comment by resouer** [comment]
Also synced with @wonderflow a bit. In general, `Application` and `Deployment` are two higher level abstractions currently missing in OAM.

`Application` is a UI object for dev to represent his application as whole.

```yaml
apiVersion: core.oam.dev/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: default
spec:
  components:
  - name: myservice
    ingress:
      route: "/test"
    replicas: 1
    container:
      name: myservice
      image: some/nodeserver:v1
      ports:
      - containerPort: 3000
      env:
      - name: VERSION
        value: "CPU HEAVY"
    auto-scale:
      minReplicas: 1
      maxReplicas: 5
      rules:
      - metric: CPU
        targetAveragePercent: 20
```

This object is mutable and will generate immutable OAM objects by either CLI or OAM runtime. In above example, a `myservice` Component and a `myapp` AppConfig with corresponding traits. This is exactly the `appfile` in vela, and we use CUE to enforce its schema.

The difference is, in Haishi's proposal, he assumes OAM objects are immutable (which was before). So the rollout/rollback of the application will need to be handled by another object named `Deployment`. 

But this assumption also stands if we want to do application level rollout (today, we do component level rollout). This would worth a design.

**Comment by resouer** [comment]
So the workflow is:

1. User create `Application` object named `my-app`
2. CLI/OAM runtime generate component and appconfig, all named with `-v1` surfix.
3. User create `Deployment` object named `my-deploy`, reference `my-app` like below:

```yaml
apiVersion: core.oam.dev/v1alpha3
kind: Deployment
metadata:
  name: canary
spec:
  versions:
    - name: v1
      applicationRef:
        - name: my-app
          version: v1
  components:
    - website # indicates which component will accept traffic (i.e. the ingress trait)
  traffic:
    - version: v1
      weight: 100%
```

4. User update `my-app`.
5. CLI/OAM runtime generate component and appconfig, all named with `-v2` surfix.
6. User update `my-deploy` to [this one](https://github.com/oam-dev/spec/issues/342#issue-588587747) to do canary rollout.

This is how we enable application level rollout (and component level rollout will be disable in this case).
