### ISSUE TITLE
Propose to use json-patch way to represent fieldPath

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#344]
I noticed our OAM fieldPath use a way almost the same with [json-patch](http://jsonpatch.com/), the only difference is json-patch use `/` to separate field while OAM fieldPath use dot `.` and the array represent way.

OAM fieldPath current way:

```
  parameters: 
  - name: imageName
    required: false
    fieldPaths: 
    - ".spec.containers[0].image"
  - name: cacheSecret
    required: true
    fieldPaths:
    - ".spec.containers[0].env[0].value"
```

json-patch way:

```
  parameters: 
  - name: imageName
    required: false
    fieldPaths: 
    - "/spec/containers/0/image"
  - name: cacheSecret
    required: true
    fieldPaths:
    - "/spec/containers/0/env/0/value"
```

I propose this because K8s use json-patch in [admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#response), users will feel more comfortable if we follow this way.

Also we could use this [json-path tool](https://github.com/evanphx/json-patch) to implement.
