### ISSUE TITLE
[Discussion][Component] New structure for Component object

### ISSUE THREAD

**Issue by resouer** [oam-dev/spec#372]
With [revision mechanism of OAM](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/one-pager-component-mutable-and-versioning.md) is introduced in, we may want to consider simplify Component object because its `spec` field is actually unneeded. Please consider the following options:

### Option 1:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: frontend
workload:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-workload
  spec:
    containers:
      - name: my-cool-workload
        image: 'example/very-cool-workload:0.1.2@sha256:verytrustworthyhash'
parameters:
  - name: imageName
    required: false
    fieldPaths:
      - 'spec.containers[0].image'
```
### Option 2:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: frontend
template:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-workload
  spec:
    containers:
      - name: my-cool-workload
        image: 'example/very-cool-workload:0.1.2@sha256:verytrustworthyhash'
parameters:
  - name: imageName
    required: false
    fieldPaths:
      - 'spec.containers[0].image'
```

/cc @negz @wonderflow @hongchaodeng @ryanzhang-oss @artursouza @hasheddan 

If we decide to go to this change, I was open to include this in `v1alpha2` since it's still pre-release stage.

**Comment by wonderflow** [comment]
I'm afraid this is conflict with [K8s API convention](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status).

**Comment by zzxwill** [comment]
@wonderflow Do you mean `spec` is a must-have which represents `the specification of the desired state of an object`? @resouer I didn't get where to put important containers properties like `port`, `env` if `its spec field is actually unneeded`. Please help clarify my confusion, thanks.

**Comment by wonderflow** [comment]
@zzxwill  Yes, for K8s object, the hierarchy is always like :

```
apiVersion:
kind:
spec:
status:
```

**Comment by hongchaodeng** [comment]
@wonderflow 

This is not true. spec and status are just conventions are hard rules. Some resource like Secret have such structure:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: abc
data:
  ...
```

**Comment by resouer** [comment]
Yes, I think the convention is not the blocker.

Just not very sure if this has benefits. So open for discussion and definitely no rush on it.

**Comment by artursouza** [comment]
I am all in for reducing verbosity in OAM. Why not simplify it even more and remove spec from Workload? Each workload would refer to different attributes but the "spec" is not needed, really.

```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: frontend
workload:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-workload
  containers:
    - name: my-cool-workload
      image: 'example/very-cool-workload:0.1.2@sha256:verytrustworthyhash'
parameters:
  - name: imageName
    required: false
    fieldPaths:
      - 'spec.containers[0].image'
```
