### ISSUE TITLE
Remove Componens

### ISSUE THREAD

**Issue by erdun** [oam-dev/spec#373]
The design of Componens and Workload is not elegant. We should define workload and component both. Remove `Component` and add crd `parameters`.

```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - workloadName: frontend
       workloadKind: ContainerizedWorkload
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: FancyTrait
            spec:
              traffic:
                - revisionName: frontend-c8bb659c5
                # revision: 1  # optional here, which can replace revisionName for UX              
                  percent: 80%
                - revision: latest
                  percent: 20%  
---
apiVersion: core.oam.dev/v1alpha2
kind: ContainerizedWorkload
metadata:
  name: frontend-c8bb659c5
spec:
  containers:
  - name: my-cool-workload
    image: example/very-cool-workload:0.1.2@sha256:verytrustworthyhash
    cmd:
    - "bash lscpu"
---
apiVersion: core.oam.dev/v1alpha2
kind: Parameter
metadata:
  name: frontend-c8bb659c5
spec:
  ref:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    name: frontend-c8bb659c5
  parameters:
  - name: instance-name
    required: true
    fieldPaths:
      - metadata.name
  - name: image
    fieldPaths:
      - spec.containers[0].image
```
