### ISSUE TITLE
Define workload types, replicable, and podspecable and make appliesTo work properly

### ISSUE THREAD

**Issue by resouer** [oam-dev/spec#392]
See this comment in OAM k8s runtime:

https://github.com/crossplane/oam-kubernetes-runtime/issues/174#issuecomment-676591957

`Server|Worker|Task` is exactly with same meaning with `v1alpha1`.

So `appliesTo` will work like this:

```yaml
appliestTo:
  - workload.oam.dev/type=server
  - workload.oam.dev/replicable=true
  - foo=bar  # arbitrary label
  - *.apps.k8s.io # api group
  - cloneset.apps.alibaba-inc.com # arbitrary API resource
```

**Comment by resouer** [comment]
We should not assume Definition always has same name with `defitionRef`.

**Comment by hongchaodeng** [comment]
We should probably make appliesTo more intelligent:

```yaml
  appliestTo:
  - group: apps
    kinds: Deployment, StatefulSet
    labelSelector:
      workload.oam.dev/podSpecable=true
  - ...
```

Then in each WorkloadDefinition we could add the hints into their labels:
```yaml
kind: WorkloadDefinition
metadata:
  labels:
    workload.oam.dev/replicable: true # can be scale
    workload.oam.dev/podspecable: true # can be addressed by k8s podSpec
```
