### ISSUE TITLE
Scope parameter dependencies

### ISSUE THREAD

**Issue by macolso** [oam-dev/spec#4]
Scope parameters have a "required" attribute that declares whether or not a value _must_ be provided for a parameter. 

How do we want to handle cases where a set of parameters A & B are optional, but if the application operator does decide they want to provide a value for A they MUST provide a value for B? For example, an application operator might want to send their logs to a pre-existing Log Analytics workspace. They have the option to have Hydra provision a workspace automatically or explicitly connect their Health Scope to a preexisting workspace; but, if they choose the latter then they need to provide **both** a WorkspaceId and WorkspaceKey. 

```yaml
schemaVersion: core.hydra.io/v1alpha1
kind: ApplicationScope
metadata:
  name: myHealthScope
  description: main healthscope for my applicaton
spec:
  type: core.hydra.io/v1.HealthScope
  parameters:
    - name: HealthThresholdPercentage
      description: the percentage of components within a scope that must be healthy to complete an update
      type: int
      required: true
      default: 80
    - name: LogAnalyticsWorkspaceId
      description: an Id for a unique environment for Azure Monitor log data
      type: string
      required: false
    - name: LogAnalyticsWorkspaceKey
      description: a key for a unique environment for Azure Monitor log data
      type: string
      required: false
```
Below is the only way to author the operational configuration file if the application operator wants to use a preexisting Log Analytics workspace:
```yaml
schemaVersion: alpha1
kind: OperationalConfiguration
metadata:
    name: custom-single-app
    description: Customized version of single-app
spec:
  components:
    - componentName: votingweb
      instanceName: voting-web-v1
      scopes:
        - name: healthScope
          type: core.hydra.io/v1alpha1.HealthScope
          parameterValues:
            - name: HealthThresholdPercentage
              value: 80
            - name: LogAnalyticsWorkspaceId
              value: d0bd5fdf-d2d8-488d-946c-97c29896e663
            - name: LogAnalyticsWorkspaceKey
              value: Kjd4S6nLFRbQfaPP8svIx42t+Vus9A1Ob9iEX/29tvkeLAI0nAq9bJUJsFbMXCnFBIJ4XpreFJFlQPae0/ezuQ==
```
However, based off of the scope schematic the following operational configuration file appears valid to the application operator even though the deployment would fail:
```yaml
schemaVersion: alpha1
kind: OperationalConfiguration
metadata:
    name: custom-single-app
    description: Customized version of single-app
spec:
  components:
    - componentName: votingweb
      instanceName: voting-web-v1
      scopes:
        - name: healthScope
          type: core.hydra.io/v1alpha1.HealthScope
          parameterValues:
            - name: HealthThresholdPercentage
              value: 80
            - name: LogAnalyticsWorkspaceId
              value: d0bd5fdf-d2d8-488d-946c-97c29896e663
```
This is a fairly simple example, but I could see this getting frustrating/confusing for the user as the number of parameters grows. Or is the goal to keep the number of parameters fairly limited so that it would be immediately obvious to users?
