### ISSUE TITLE
Expectation related to instantiating components on ApplicationConfiguration

### ISSUE THREAD

**Issue by dhiguero** [oam-dev/spec#429]
We have found an issue related to the expectations of what happens with a component on an _ApplicationConfiguration_ entity. Launching the [containerized-workload](https://github.com/crossplane/oam-kubernetes-runtime/tree/master/examples/containerized-workload) example once, and then copying the _ApplicationConfiguration_, changing its name, and launching it again produces the following output:

```
"status": {
        "conditions": [
            {
                "lastTransitionTime": "2021-01-14T15:42:04Z",
                "message": "cannot apply components: cannot apply workload \"example-component\": existing object is not controlled by UID \"40502b95-8c1a-4353-884d-94e23bdffbc0\"",
                "reason": "ReconcileError",
                "status": "False",
                "type": "Synced"
            }
        ],
        "dependency": {},
        "observedGeneration": 1
    }
```

On the _ApplicationConfiguration_ [spec](https://github.com/oam-dev/spec/blob/master/7.application_configuration.md#component) related to the `component` it says

> The name of the component of which to create an instance. The revision of this instance will always reflect the latest change of the component (i.e. always track latest revision). This is mutually exclusive with revisionName.” so we understood that a component once defined can be reused by many application configurations.

We believe this is a desired and expected outcome since it will improve reusability and we already have a `parameterValues` attribute. In this way, we think that having reusable components among different _ApplicationConfigurations_ would be ideal. From other parts of the [spec](https://github.com/oam-dev/spec/blob/master/3.component.md#3-components), this approach seems to be expected 

> Components describe functional units that may be instantiated as part of a larger distributed application. For example, each microservice in an application is described as a component. The description itself is not an instance of that microservice, but a declaration of the operational capabilities of that microservice.

We are aware of other proposed entities such as the [ComponentSchematic](https://github.com/oam-dev/spec/blob/master/design/20200105-spec-v1alpha2-kubernetes-friendly.md#background) which are defined as

> ... can be either a template for configuration values according to a fixed schema (the containers array), or define both schema and configuration values (the workloadSettings object)

One alternative to introduce this feature using the current entities could be to modify the _ApplicationConfiguration_ to include a new reference so it is clear for the runtime that we expect to make a new copy of a component (creating a new instance) instead of linking it to an existing one:

```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - componentName: my-new-example-component
      parameterValues:
        - name: image
          value: wordpress:php7.2
      componentRef:
        apiVersion: core.oam.dev/v1alpha2
        kind: Component
        name: example-component
  ...
```

What do you think?
