### ISSUE TITLE
Catalog design

### ISSUE THREAD

**Issue by dhiguero** [oam-dev/spec#434]
Following on the last community call items, the concept of having a catalog for OAM applications is an interesting topic that is being actively developed by some of the members. In order to improve the reusability of catalogs among different solutions, we believe that it will be good to approach its definition as a community proposal so that there exists a basic definition of its layout and purpose.

**Basic layout**

We have approached the catalog trying to go for its most basic form so that an application can define all the elements that are needed considering those as (preferably OAM) YAML entities. We think that the catalog should not contain other entities such as Dockerfiles or becoming a code repository.

Based on this assumptions, we are working on a catalog with the following layout:

```
/<application>
  |- metadata.yaml
  |- README.md
  |- app_cfg.yaml
  |
  |- <opt_directory>
  |  |- OAM_entity.yaml
  |  \- K8s_entity.yaml
  |- OAM_entity.yaml
  \- K8s_entity.yaml
```

Where the YAML files are OAM entities plus basic K8s entities that follow the current OAM suggestions/workarounds for items such as secrets and configmaps. The `metadata.yaml` file contains information about the application as a whole to facilitate its discovery on the catalog. The `README.md` provides a textual description on how to use the application as found in other systems such as a GitHub repo, or the Docker Hub readme for an image. Directory structure is left for the application designer/developer to decide as the catalog engine has enough information (YAML headers containing kind and apiVersion) to identify entities.

**metatadata.yaml**

In terms of the metadata file we believe its purpose is to facilitate the discovery on the catalog by means of the different tools that may appear for exploring/integrating catalogs in OAM environments. Other similar entities are both defined on [APIServer + Catalog Architecture Design](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md) and [Application metadata descriptor CRD](https://github.com/kubernetes-sigs/application) and share similar attributes.

```yaml
apiVersion: core.oam.dev/XYZ
kind: ApplicationMetadata
# Name of the application, not necessarily a valid k8s name.
name: "My App Name"
version: 1.0
description: Short description for searchs. Long one plus how to goes into the README.md
# Tags facilitate searches on the catalog
tags:
  - "tag1"
  - "tag2"
  - "tag3" 
license: "Apache License Version 2.0"
url: "https://..."
doc: "https://..."
# Requires gives a list of entities that are needed to launch the application.
requires:
  traits:
    - my.custom.trait
  scopes:
    - my.custom.scope
  crd:
    - my.custom.crd
# The logo can be used as visual information when listing the catalog so the user recognizes more easily the application.
logo:
  - src: "https://my.domain/path/logo.png"
    type: "image/png"
    size: "120x120"
```

Some comments/differences with the aforementioned proposals are:

* **Labels vs tags**: We think that tags are more simpler to use as keywords for catalog searchs.
* **Emails**: While some of the approaches include contact information (emails) on the metadata, we believe having two URLs for going to the main web page, plus the documentation and having a README.md is enough to point the user into contact methods depending on their needs.
* **Requirements**: As traits, scopes or in general other CRD an application may need have a collateral impact or requiring installing the appropiate operators, we think that is important to facilitate identifying whether an application can be deployed in a given cluster or a new element must be installed at cluster level. Installing traits and scope is another topic that may need further discussion as it has many collateral impacts in a multi-tenant cluster.

What do you think?
