### ISSUE TITLE
Component: combine WorkloadSettings and Parameters?

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/spec#49]
Currently there is `parameters` defined in Component, and `workloadSettings` is parameters that are passed into `workload`. But as a spec writer I end up duplicating a lot of parameters by passing them as:

```
  workloadSettings:
    - name: app-format
      fromParam: app-format
    - name: jdk-version
      fromParam: jdk-version
    ... 
```

My question is why workload needs different settings? Isn't `Parameters` the key-values that we want to pass into this workload already?
