### ISSUE TITLE
Where will the Application Metadata be defined

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#87]
Now we have Configuration to combine multiple components together which define an Application instance, but if we want to define multiple applications and there will be some dependency on these applications. So we may need a place (or a concept) to define Application Metadata.

Application Metadata is used to store application level information, such as application logo, providers, maintainers, dependencies, etc. We will be able to launch a set of applications if we have defined the application metadata.

For example, we define this Application Meta
```
apiVersion: core.hydra.io/v1alpha1
kind: ApplicationMeta
metadata:
  labels:
    version: 1.0.0   
spec:
  appName: edas-console
  maintainer: hydra
  logo: /path/to/logo.svg
  components:
    - name: comp1
      metadata:
        version: 1.0.0
        componentRef: compx
    - name: comp2
      metadata:
        version: 1.2.0
        componentRef: compy 
  dependency: 
    - zookeeper
    - kafka      
  parameters:
    - name: parma1
      value: value1
```

With ApplicationMeta we will be able to define application relationships.
