### ISSUE TITLE
ReplicaCount Parameter missing for ReplicatedService workload type

### ISSUE THREAD

**Issue by macolso** [oam-dev/spec#9]
We have the following example in our [Operational Configuration](6.operational_configuration.md) page:

```yaml
apiVersion: core.hydra.io/v1alpha1
kind: ComponenSchematic
metadata:
  name: frontend
  version: "1.0.0"
  description: A simple webserver
spec:
  workloadType: core.hydra.io/v1.ReplicatedService
  parameters:
    - name: message
      description: The message to display in the web app.
      type: string
      value: "Hello from my app, too"
  containers:
    - name: web
      env:
        - name: MESSAGE
          fromParam: message
      image:
        name: technosophos/charybdis-single:latest
```
```yaml
apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
  name: custom-single-app
  description: Customized version of single-app
spec:
  parameters:
    - name: message
      value: "Well hello there"
  components:
    componentName: frontend
    instanceName: web-front-end
    parameterValues:
      - name: message
        fromParam: message
```
Even though frontend component is a replicatedService, we don't have a parameter explicitly listing how many replicas should be instantiated.  I propose we consider replica count an app ops concern and place it in the operational config file. See below for corrected example:
```yaml
apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
  name: custom-single-app
  description: Customized version of single-app
spec:
  parameters:
    - name: message
      value: "Well hello there"
  components:
    componentName: frontend
    replicaCount: 3
    instanceName: web-front-end
    parameterValues:
      - name: message
        fromParam: message
```
Thoughts?
