### ISSUE TITLE
Support loading parameters from different data sources

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/spec#90]
Currently, writing a Configuration yaml requires filling in all parameters one by one. It would be convenient if we can load the parameter values from data sources automatically. For example, 
a ConfigMap have application data:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-env
data:
  SERVER_DOMAIN: internal.my-company.com
  SERVER_PORT: "80"
```

```yaml
apiVersion: core.hydra.io/v1alpha1
kind: Configuration
spec:
  parametersFrom:
    configMapRef: server-env
```

Secondly, we want to load it from different sources like k8s ConfigMap, etcd.
